In [1]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.

# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.

# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.

# 4. Create a tf.Variable with initial value 5.0 and print its current value.

# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.

# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.

# 7. Create a variable x = 3.0 and inside a tf.GradientTape() block compute y = x**2 + 2*x + 1, then print both x and y.

# 8. Compute the gradient dy/dx for y = x**2 + 2*x + 1 using tf.GradientTape() and print the gradient value.

# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().

# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.


In [14]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.
import tensorflow as tf
scalar = tf.constant(10)
print(f"Scalar value: {scalar.numpy()}, Data type: {scalar.dtype}")

Scalar value: 10, Data type: <dtype: 'int32'>


In [12]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.
vector = tf.constant([2, 4, 6, 8])
print(f"Vector shape: {vector.shape}, value: {vector.numpy()}")

Vector shape: (4,), value: [2 4 6 8]


In [19]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.
matrix = tf.constant([[1, 2], [3, 4]])
print(f"Matrix shape: {matrix.shape}, Matrix dtype:", matrix.dtype)

Matrix shape: (2, 2), Matrix dtype: <dtype: 'int32'>


In [20]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.
var = tf.Variable(5.0)
print(f"Variable initial value:", var.numpy())

Variable initial value: 5.0


In [22]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.
var.assign(10.0)
print(f"Updated variable value:", var.numpy())

Updated variable value: 10.0


In [25]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.
var_matrix = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
var_matrix.assign_add([[1.0, 1.0], [1.0, 1.0]])
print("After assign_add():")
print(var_matrix.numpy())

After assign_add():
[[2. 3.]
 [4. 5.]]


In [26]:
# 7. Create a variable x = 3.0 and inside a tf.GradientTape() block compute y = x**2 + 2*x + 1, then print both x and y.
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 2*x + 1
print(f"x value:", x.numpy())
print(f"y value:", y.numpy())

x value: 3.0
y value: 16.0


In [27]:
# 8. Compute the gradient dy/dx for y = x**2 + 2*x + 1 using tf.GradientTape() and print the gradient value.
grad = tape.gradient(y, x)
print(f"Gradient dy/dx:", grad.numpy())

Gradient dy/dx: 8.0


In [28]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
matmul_result = tf.matmul(a, b)
print(f"Matrix multiplication result:",matmul_result.numpy())

Matrix multiplication result: [[19 22]
 [43 50]]


In [29]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.
random_tensor = tf.random.uniform((3, 3))
print(f"Random tensor shape:", random_tensor.shape)
print(f"Random tensor dtype:", random_tensor.dtype)
print(f"Random tensor values:\n", random_tensor.numpy())

Random tensor shape: (3, 3)
Random tensor dtype: <dtype: 'float32'>
Random tensor values:
 [[0.6729425  0.38425708 0.77952015]
 [0.27760506 0.30317163 0.87083507]
 [0.6281092  0.95332956 0.15921044]]
